language: node_js
node_js:
- lts/boron
- node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KvanBnSlzQFSj+hMzeYhDppLbHaZHwr3X4YkbsLneQCGHBsqHvpkoRcgh/0YxIUBo/XZUD1Q4bR1FzhSuN8INom0D8DYa8wsoSBnG+IWv4GSosVw+DFMoMOwZLGAlnVQLrP9d0hkoprHIc8th6pv9+Zy2DZx22ljdYKTOgFT4ns=
  file:
    - "mdast-zone.js"
    - "mdast-zone.min.js"
  on:
    tags: true
